#Selection

In [3]:
import pandas as pd
df = pd.read_csv('/ramen-ratings.csv')

In [9]:
df

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1,NaN
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN
...,...,...,...,...,...,...,...
2575,5,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Bowl,Vietnam,3.5,NaN
2576,4,Wai Wai,Oriental Style Instant Noodles,Pack,Thailand,1,NaN
2577,3,Wai Wai,Tom Yum Shrimp,Pack,Thailand,2,NaN
2578,2,Wai Wai,Tom Yum Chili Flavor,Pack,Thailand,2,NaN
2579,1,Westbrae,Miso Ramen,Pack,USA,0.5,NaN

In [5]:
df.head()

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1,NaN
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN

In [6]:
df.loc[0:9]

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1,NaN
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN
5,2575,Samyang Foods,Kimchi song Song Ramen,Pack,South Korea,4.75,NaN
6,2574,Acecook,Spice Deli Tantan Men With Cilantro,Cup,Japan,4,NaN
7,2573,Ikeda Shoku,Nabeyaki Kitsune Udon,Tray,Japan,3.75,NaN
8,2572,Ripe'n'Dry,Hokkaido Soy Sauce Ramen,Pack,Japan,0.25,NaN
9,2571,KOKA,The Original Spicy Stir-Fried Noodles,Pack,Singapore,2.5,NaN

In [7]:
df.iloc[0:10][:]

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1,NaN
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN
5,2575,Samyang Foods,Kimchi song Song Ramen,Pack,South Korea,4.75,NaN
6,2574,Acecook,Spice Deli Tantan Men With Cilantro,Cup,Japan,4,NaN
7,2573,Ikeda Shoku,Nabeyaki Kitsune Udon,Tray,Japan,3.75,NaN
8,2572,Ripe'n'Dry,Hokkaido Soy Sauce Ramen,Pack,Japan,0.25,NaN
9,2571,KOKA,The Original Spicy Stir-Fried Noodles,Pack,Singapore,2.5,NaN

In [8]:
df.tail()

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
2575,5,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Bowl,Vietnam,3.5,NaN
2576,4,Wai Wai,Oriental Style Instant Noodles,Pack,Thailand,1,NaN
2577,3,Wai Wai,Tom Yum Shrimp,Pack,Thailand,2,NaN
2578,2,Wai Wai,Tom Yum Chili Flavor,Pack,Thailand,2,NaN
2579,1,Westbrae,Miso Ramen,Pack,USA,0.5,NaN

In [13]:
df.loc[2560:2565 , [ 'Brand','Stars']]

          Brand Stars
2560   Nongshim   3.5
2561   Nongshim     4
2562     Ottogi   3.5
2563  Quickchow   2.5
2564    Samyang   3.5
2565    Samyang   2.5

#  Conditional Selection

In [16]:
df[:] == 'Japan'

      Review #  Brand  Variety  Style  Country  Stars  Top Ten
0        False  False    False  False     True  False    False
1        False  False    False  False    False  False    False
2        False  False    False  False    False  False    False
3        False  False    False  False    False  False    False
4        False  False    False  False    False  False    False
...        ...    ...      ...    ...      ...    ...      ...
2575     False  False    False  False    False  False    False
2576     False  False    False  False    False  False    False
2577     False  False    False  False    False  False    False
2578     False  False    False  False    False  False    False
2579     False  False    False  False    False  False    False

[2580 rows x 7 columns]

In [4]:
df.loc[df['Country']== 'Japan']

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
6,2574,Acecook,Spice Deli Tantan Men With Cilantro,Cup,Japan,4,NaN
7,2573,Ikeda Shoku,Nabeyaki Kitsune Udon,Tray,Japan,3.75,NaN
8,2572,Ripe'n'Dry,Hokkaido Soy Sauce Ramen,Pack,Japan,0.25,NaN
13,2567,Nissin,Deka Buto Kimchi Pork Flavor,Bowl,Japan,4.5,NaN
...,...,...,...,...,...,...,...
2554,26,Nissin,Soba Noodles With Mayo Mustard Squirt,Pack,Japan,4,NaN
2555,25,Nissin,Demae Ramen Spicy Flavor,Pack,Japan,3,NaN
2556,24,Nissin,Demae Ramen Spicy Seafood With Chili Pepper,Pack,Japan,2,NaN
2567,13,Sapporo Ichiban,Chow Mein,Pack,Japan,5,2012 #4
2568,12,Sapporo Ichiban,Shrimp Flavor,Pack,Japan,2.5,NaN

In [16]:
df['Stars'].str.replace('Unrated','0')

0       3.75
1          1
2       2.25
3       2.75
4       3.75
        ...
2575     3.5
2576       1
2577       2
2578       2
2579     0.5
Name: Stars, Length: 2580, dtype: object

In [18]:
df['Stars'] = df['Stars'].str.replace('Unrated','0')

In [36]:
df['Stars'] = df['Stars'].astype('float')

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2580 entries, 0 to 2579
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Review #  2580 non-null   int64
 1   Brand     2580 non-null   object
 2   Variety   2580 non-null   object
 3   Style     2578 non-null   object
 4   Country   2580 non-null   object
 5   Stars     2580 non-null   float64
 6   Top Ten   41 non-null     object
dtypes: float64(1), int64(1), object(5)
memory usage: 141.2+ KB

In [29]:
df['Stars'].unique()

array(['3.75', '1', '2.25', '2.75', '4.75', '4', '0.25', '2.5', '5',
       '4.25', '4.5', '3.5', '0', '1.5', '3.25', '2', '3', '0.5', '4.00',
       '5.0', '3.50', '3.8', '4.3', '2.3', '5.00', '3.3', '4.0', '3.00',
       '1.75', '3.0', '4.50', '0.75', '1.25', '1.1', '2.1', '0.9', '3.1',
       '4.125', '3.125', '2.125', '2.9', '0.1', '2.8', '3.7', '3.4',
       '3.6', '2.85', '3.2', '3.65', '1.8'], dtype=object)

In [38]:
df['Stars'] > 4.5

0       False
1       False
2       False
3       False
4       False
        ...
2575    False
2576    False
2577    False
2578    False
2579    False
Name: Stars, Length: 2580, dtype: bool

In [40]:
df.loc[(df['Style'] == 'Cup') | (df['Country'] == 'USA')]

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
6,2574,Acecook,Spice Deli Tantan Men With Cilantro,Cup,Japan,4.00,NaN
11,2569,Yamachan,Yokohama Tonkotsu Shoyu,Pack,USA,5.00,NaN
15,2565,KOKA,Mushroom Flavour Instant Noodles,Cup,Singapore,3.50,NaN
...,...,...,...,...,...,...,...
2546,34,Maruchan,Ramen Noodle Soup Shrimp,Pack,USA,2.00,NaN
2557,23,Nissin,Top Ramen Creamy Chicken,Pack,USA,4.50,NaN
2570,10,Smack,Vegetable Beef,Pack,USA,1.50,NaN
2571,9,Sutah,Cup Noodle,Cup,South Korea,2.00,NaN
2579,1,Westbrae,Miso Ramen,Pack,USA,0.50,NaN

#Assign New Column

In [44]:
def rating (row):
    if row['Stars'] >= 4:
        return 'Excellent'
    else:
        return 'Good'

In [45]:
df['Status'] = df.apply(rating, axis=1)

In [47]:
df.head(20)

,Review #,Brand,Variety,Style,Country,Stars,Top Ten,Status
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN,Good
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1.00,NaN,Good
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN,Good
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN,Good
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN,Good
5,2575,Samyang Foods,Kimchi song Song Ramen,Pack,South Korea,4.75,NaN,Excellent
6,2574,Acecook,Spice Deli Tantan Men With Cilantro,Cup,Japan,4.00,NaN,Excellent
7,2573,Ikeda Shoku,Nabeyaki Kitsune Udon,Tray,Japan,3.75,NaN,Good
8,2572,Ripe'n'Dry,Hokkaido Soy Sauce Ramen,Pack,Japan,0.25,NaN,Good
9,2571,KOKA,The Original Spicy Stir-Fried Noodles,Pack,Singapore,2.50,NaN,Good
10,2570,Tao Kae Noi,Creamy tom Yum Kung Flavour,Pack,Thailand,5.00,NaN,Excellent
11,2569,Yamachan,Yokohama Tonkotsu Shoyu,Pack,USA,5.00,NaN,Excellent
12,2568,Nongshim,Mr. Bibim Stir-Fried Kimchi Flavor,Pack,South Korea,4.25,NaN,Excellent
13,2567,Nissin,Deka Buto Kimchi Pork Flavor,Bowl,Japan,4.50,NaN,Excellent
14,2566,Nissin,Demae Ramen Bar Noodle Aka Tonkotsu Flavour In...,Pack,Hong Kong,5.00,NaN,Excellent
15,2565,KOKA,Mushroom Flavour Instant Noodles,Cup,Singapore,3.50,NaN,Good
16,2564,TRDP,Mario Masala Noodles,Pack,India,3.75,NaN,Good
17,2563,Yamachan,Tokyo Shoyu Ramen,Pack,USA,5.00,NaN,Excellent
18,2562,Binh Tay,Mi Hai Cua,Pack,Vietnam,4.00,NaN,Excellent
19,2561,Paldo,Premium Gomtang,Pack,South Korea,4.00,NaN,Excellent