## Import library

In [9]:
import pandas as pd
import numpy as np

## Read Data

In [3]:
df = pd.read_csv('/content/Weather.csv')

## shows the first N rows in the data (by default, N=5)

In [7]:
df.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog

## shows the total no of rows and no. of columns of the dataframe

In [10]:
df.count('rows')

Date/Time           8784
Temp_C              8784
Dew Point Temp_C    8784
Rel Hum_%           8784
Wind Speed_km/h     8784
Visibility_km       8784
Press_kPa           8784
Weather             8784
dtype: int64

In [11]:
df.count('columns')

0       8
1       8
2       8
3       8
4       8
       ..
8779    8
8780    8
8781    8
8782    8
8783    8
Length: 8784, dtype: int64

## Show the index of the data frame

In [14]:
df.index

RangeIndex(start=0, stop=8784, step=1)

## shows the name of each column

In [6]:
df.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')

## Show the info of all columns

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   object
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

## Show unique values in Weather column

In [7]:
df['Weather'].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 'Rain,Snow Grains', 'Rain,Snow,Ice Pellets',
       'Snow Showers,Fog', 'Moderate Snow,Blowing Snow'], dtype=object)

## Shows the number of unique values for each column

In [16]:
#for col in df.columns:
  #  print(f"Column '{col}': {df[col].nunique()} unique values")

df['Weather'].nunique()

50

## Show the count of values for each column

In [17]:
df['Weather'].value_counts()

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Freezing Drizzle,Fog                          6
Snow,Ice Pellets                              6
Snow,Haze                                     5
Freezing Rain,Fog                             4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Fog                                  4
Snow Showers,Fog                              4
Thunderstorms,Rain Showers,Fog                3
Thunderstorms,Rain                            3
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Drizzle,Snow                                  2
Moderate Snow,Blowing Snow                    2
Thunderstorms                                 2
Freezing Rain,Haze                            2
Rain Showers,Snow Showers                     2
Freezing Rain,Snow Grains                     1
Thunderstorms,Heavy Rain Showers              1
Thunderstorms,Moderate Rain Showers,Fog       1
Thunderstorms,Rain,Fog                        1
Freezing Rain,Ice Pellets,Fog                 1
Moderate Rain,Fog                             1
Rain,Snow,Fog                                 1
Snow Pellets                                  1
Rain Showers,Fog                              1
Drizzle,Ice Pellets,Fog                       1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Name: count, dtype: int64

## Q. 1)  Find all the unique 'Wind Speed' values in the data.

In [19]:
df['Wind Speed_km/h'].unique()

array([ 4,  7,  6,  9, 15, 13, 20, 22, 19, 24, 30, 35, 39, 32, 33, 26, 44,
       43, 48, 37, 28, 17, 11,  0, 83, 70, 57, 46, 41, 52, 50, 63, 54,  2])

## Q. 2) Find the number of times when the 'Weather is exactly Clear'.

In [27]:
(df["Weather"] == "Clear").sum()

np.int64(1326)

## Q. 3) Find the number of times when the 'Wind Speed was exactly 4 km/h'.

In [23]:
#if 'Wind Speed_km/h' == 4:
  #print('Wind Speed was exactly 4 km/h')
#else:
 # print('Wind Speed was not exactly 4 km/h')

Wind Speed was not exactly 4 km/h

In [26]:
(df['Wind Speed_km/h'] == 4).sum()

np.int64(474)

In [24]:
df.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog

## Q. 4) Find out all the Null Values in the data.

In [28]:
df.isnull().sum()

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

## Q. 5) Rename the column name 'Weather' of the dataframe to 'Weather Condition'.

In [29]:
df = df.rename(columns={'Weather': 'Weather Condition'})

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date/Time          8784 non-null   object
 1   Temp_C             8784 non-null   float64
 2   Dew Point Temp_C   8784 non-null   float64
 3   Rel Hum_%          8784 non-null   int64
 4   Wind Speed_km/h    8784 non-null   int64
 5   Visibility_km      8784 non-null   float64
 6   Press_kPa          8784 non-null   float64
 7   Weather Condition  8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

## Q. 6) What is the mean 'Visibility' ?

In [35]:
df['Visibility_km'].mean()

np.float64(27.664446721311478)

## Q. 7) What is the Standard Deviation of 'Pressure'  in this data?

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date/Time          8784 non-null   object
 1   Temp_C             8784 non-null   float64
 2   Dew Point Temp_C   8784 non-null   float64
 3   Rel Hum_%          8784 non-null   int64
 4   Wind Speed_km/h    8784 non-null   int64
 5   Visibility_km      8784 non-null   float64
 6   Press_kPa          8784 non-null   float64
 7   Weather Condition  8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

In [37]:
df['Press_kPa'].std()

0.8440047459486474

## Q. 8) What is the Variance of Relative Humidity (Rel Hum_%) in this data ?

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date/Time          8784 non-null   object
 1   Temp_C             8784 non-null   float64
 2   Dew Point Temp_C   8784 non-null   float64
 3   Rel Hum_%          8784 non-null   int64
 4   Wind Speed_km/h    8784 non-null   int64
 5   Visibility_km      8784 non-null   float64
 6   Press_kPa          8784 non-null   float64
 7   Weather Condition  8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

In [39]:
df['Rel Hum_%'].var()

286.2485501984998

## Q. 9) Find all instances when 'Snow' was recorded.

In [43]:
df.loc[df['Weather Condition'] == "Snow"]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
55,1/3/2012 7:00,-14.0,-19.5,63,19,25.0,100.95,Snow
84,1/4/2012 12:00,-13.7,-21.7,51,11,24.1,101.25,Snow
86,1/4/2012 14:00,-11.3,-19.0,53,7,19.3,100.97,Snow
87,1/4/2012 15:00,-10.2,-16.3,61,11,9.7,100.89,Snow
88,1/4/2012 16:00,-9.4,-15.5,61,13,19.3,100.79,Snow
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

## Q. 10) Find all instances when 'Wind Speed is above 24' and 'Visibility is 25'.

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date/Time          8784 non-null   object
 1   Temp_C             8784 non-null   float64
 2   Dew Point Temp_C   8784 non-null   float64
 3   Rel Hum_%          8784 non-null   int64
 4   Wind Speed_km/h    8784 non-null   int64
 5   Visibility_km      8784 non-null   float64
 6   Press_kPa          8784 non-null   float64
 7   Weather Condition  8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

In [48]:
df.loc[(df['Wind Speed_km/h'] > 24) & (df['Visibility_km'] == 25)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
23,1/1/2012 23:00,5.3,2.0,79,30,25.0,99.31,Cloudy
24,1/2/2012 0:00,5.2,1.5,77,35,25.0,99.26,Rain Showers
25,1/2/2012 1:00,4.6,0.0,72,39,25.0,99.26,Cloudy
26,1/2/2012 2:00,3.9,-0.9,71,32,25.0,99.26,Mostly Cloudy
27,1/2/2012 3:00,3.7,-1.5,69,33,25.0,99.30,Mostly Cloudy
...,...,...,...,...,...,...,...,...
8705,12/28/2012 17:00,-8.6,-12.0,76,26,25.0,101.34,Mainly Clear
8753,12/30/2012 17:00,-12.1,-15.8,74,28,25.0,101.26,Mainly Clear
8755,12/30/2012 19:00,-13.4,-16.5,77,26,25.0,101.47,Mainly Clear
8759,12/30/2012 23:00,-12.1,-15.1,78,28,25.0,101.52,Mostly Cloudy
8760,12/31/2012 0:00,-11.1,-14.4,77,26,25.0,101.51,Cloudy

## Q. 11) What is the Mean value of each column against each 'Weather Condition ?

In [52]:
df.groupby("Weather Condition")["Wind Speed_km/h"].mean()

Weather Condition
Clear                                      10.557315
Cloudy                                     16.127315
Drizzle                                    16.097561
Drizzle,Fog                                11.862500
Drizzle,Ice Pellets,Fog                    20.000000
Drizzle,Snow                               14.000000
Drizzle,Snow,Fog                           15.533333
Fog                                         7.946667
Freezing Drizzle                           16.571429
Freezing Drizzle,Fog                       17.000000
Freezing Drizzle,Haze                      10.333333
Freezing Drizzle,Snow                      16.272727
Freezing Fog                                4.750000
Freezing Rain                              19.214286
Freezing Rain,Fog                          15.500000
Freezing Rain,Haze                          7.500000
Freezing Rain,Ice Pellets,Fog              28.000000
Freezing Rain,Snow Grains                  32.000000
Haze                                       10.437500
Mainly Clear                               14.144824
Moderate Rain,Fog                          17.000000
Moderate Snow                              33.750000
Moderate Snow,Blowing Snow                 40.000000
Mostly Cloudy                              15.813920
Rain                                       19.254902
Rain Showers                               17.132979
Rain Showers,Fog                           13.000000
Rain Showers,Snow Showers                  22.500000
Rain,Fog                                   14.793103
Rain,Haze                                  11.666667
Rain,Ice Pellets                           24.000000
Rain,Snow                                  28.388889
Rain,Snow Grains                           26.000000
Rain,Snow,Fog                               9.000000
Rain,Snow,Ice Pellets                      23.250000
Snow                                       20.038462
Snow Pellets                               35.000000
Snow Showers                               19.233333
Snow Showers,Fog                           13.750000
Snow,Blowing Snow                          34.842105
Snow,Fog                                   17.324324
Snow,Haze                                   5.000000
Snow,Ice Pellets                           23.833333
Thunderstorms                               7.500000
Thunderstorms,Heavy Rain Showers            9.000000
Thunderstorms,Moderate Rain Showers,Fog    15.000000
Thunderstorms,Rain                         15.666667
Thunderstorms,Rain Showers                 18.312500
Thunderstorms,Rain Showers,Fog             19.666667
Thunderstorms,Rain,Fog                     19.000000
Name: Wind Speed_km/h, dtype: float64

## Q. 12) What is the Minimum & Maximum value of each column against each 'Weather Condition ?

In [53]:
df.groupby('Weather Condition')['Wind Speed_km/h'].agg(["min", "max"])

                                         min  max
Weather Condition
Clear                                      0   33
Cloudy                                     0   54
Drizzle                                    0   30
Drizzle,Fog                                0   28
Drizzle,Ice Pellets,Fog                   20   20
Drizzle,Snow                               9   19
Drizzle,Snow,Fog                           7   32
Fog                                        0   22
Freezing Drizzle                           6   26
Freezing Drizzle,Fog                       6   33
Freezing Drizzle,Haze                      9   11
Freezing Drizzle,Snow                      6   24
Freezing Fog                               0    9
Freezing Rain                              7   28
Freezing Rain,Fog                          7   26
Freezing Rain,Haze                         6    9
Freezing Rain,Ice Pellets,Fog             28   28
Freezing Rain,Snow Grains                 32   32
Haze                                       0   17
Mainly Clear                               0   63
Moderate Rain,Fog                         17   17
Moderate Snow                             26   39
Moderate Snow,Blowing Snow                39   41
Mostly Cloudy                              0   83
Rain                                       0   52
Rain Showers                               0   41
Rain Showers,Fog                          13   13
Rain Showers,Snow Showers                 17   28
Rain,Fog                                   0   46
Rain,Haze                                  7   17
Rain,Ice Pellets                          24   24
Rain,Snow                                 13   52
Rain,Snow Grains                          26   26
Rain,Snow,Fog                              9    9
Rain,Snow,Ice Pellets                     17   28
Snow                                       0   57
Snow Pellets                              35   35
Snow Showers                               0   37
Snow Showers,Fog                           7   22
Snow,Blowing Snow                         24   48
Snow,Fog                                   4   35
Snow,Haze                                  0   15
Snow,Ice Pellets                          19   33
Thunderstorms                              0   15
Thunderstorms,Heavy Rain Showers           9    9
Thunderstorms,Moderate Rain Showers,Fog   15   15
Thunderstorms,Rain                         4   30
Thunderstorms,Rain Showers                 7   32
Thunderstorms,Rain Showers,Fog             7   35
Thunderstorms,Rain,Fog                    19   19

## Q. 13) Show all the Records where Weather Condition is Fog.

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date/Time          8784 non-null   object
 1   Temp_C             8784 non-null   float64
 2   Dew Point Temp_C   8784 non-null   float64
 3   Rel Hum_%          8784 non-null   int64
 4   Wind Speed_km/h    8784 non-null   int64
 5   Visibility_km      8784 non-null   float64
 6   Press_kPa          8784 non-null   float64
 7   Weather Condition  8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

In [60]:
df[df['Weather Condition'] == 'Fog']

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
5,1/1/2012 5:00,-1.4,-3.3,87,9,6.4,101.27,Fog
6,1/1/2012 6:00,-1.5,-3.1,89,7,6.4,101.29,Fog
...,...,...,...,...,...,...,...,...
8716,12/29/2012 4:00,-16.0,-17.2,90,6,9.7,101.25,Fog
8717,12/29/2012 5:00,-14.8,-15.9,91,4,6.4,101.25,Fog
8718,12/29/2012 6:00,-13.8,-15.3,88,4,9.7,101.25,Fog
8719,12/29/2012 7:00,-14.8,-16.4,88,7,8.0,101.22,Fog
8722,12/29/2012 10:00,-12.0,-13.3,90,7,6.4,101.15,Fog

## Q. 14) Find all instances when 'Weather is Clear' or 'Visibility is above 40'.

In [59]:
df[(df['Weather Condition'] == "Clear") | (df['Visibility_km'] > 40)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
67,1/3/2012 19:00,-16.9,-24.8,50,24,25.0,101.74,Clear
106,1/5/2012 10:00,-6.0,-10.0,73,17,48.3,100.45,Mainly Clear
107,1/5/2012 11:00,-5.6,-10.2,70,22,48.3,100.41,Mainly Clear
108,1/5/2012 12:00,-4.7,-9.6,69,20,48.3,100.38,Mainly Clear
109,1/5/2012 13:00,-4.4,-9.7,66,26,48.3,100.40,Mainly Clear
...,...,...,...,...,...,...,...,...
8749,12/30/2012 13:00,-12.4,-16.2,73,37,48.3,100.92,Mostly Cloudy
8750,12/30/2012 14:00,-11.8,-16.1,70,37,48.3,100.96,Mainly Clear
8751,12/30/2012 15:00,-11.3,-15.6,70,32,48.3,101.05,Mainly Clear
8752,12/30/2012 16:00,-11.4,-15.5,72,26,48.3,101.15,Mainly Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear

## Q. 15) Find all instances when :
*  ('Weather is Clear' and 'Relative Humidity is greater than 50') or  ('Visibility is above 40')

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date/Time          8784 non-null   object
 1   Temp_C             8784 non-null   float64
 2   Dew Point Temp_C   8784 non-null   float64
 3   Rel Hum_%          8784 non-null   int64
 4   Wind Speed_km/h    8784 non-null   int64
 5   Visibility_km      8784 non-null   float64
 6   Press_kPa          8784 non-null   float64
 7   Weather Condition  8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

In [58]:
df[((df['Weather Condition'] == "Clear") & (df['Rel Hum_%'] > 50)) | (df['Visibility_km'] > 40)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
106,1/5/2012 10:00,-6.0,-10.0,73,17,48.3,100.45,Mainly Clear
107,1/5/2012 11:00,-5.6,-10.2,70,22,48.3,100.41,Mainly Clear
108,1/5/2012 12:00,-4.7,-9.6,69,20,48.3,100.38,Mainly Clear
109,1/5/2012 13:00,-4.4,-9.7,66,26,48.3,100.40,Mainly Clear
110,1/5/2012 14:00,-5.1,-10.7,65,22,48.3,100.46,Mainly Clear
...,...,...,...,...,...,...,...,...
8749,12/30/2012 13:00,-12.4,-16.2,73,37,48.3,100.92,Mostly Cloudy
8750,12/30/2012 14:00,-11.8,-16.1,70,37,48.3,100.96,Mainly Clear
8751,12/30/2012 15:00,-11.3,-15.6,70,32,48.3,101.05,Mainly Clear
8752,12/30/2012 16:00,-11.4,-15.5,72,26,48.3,101.15,Mainly Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear